### ISSUE TITLE
build fails when there is a folder (in the path) with a space in its name

### ISSUE THREAD

**Issue by mabbamOG** [ocecaco/leveldb-sys#1]
pretty much what the title says. it's a pretty important bug when leveldb-sys ends up being used in larger projects...
OS: MacOS Catalina

**Comment by ocecaco** [comment]
Hey, thanks for the bug report, but this is just my personal (and unmaintained) fork of the `leveldb-sys` library, so you might have better luck posting at the official repo at https://github.com/skade/leveldb-sys (although I noticed you already posted there as well).

**Comment by mabbamOG** [comment]
Sorry for that @ocecaco! Will close the issue 👍
